#/usr/bin/python
################
#  orcarun.py  #
################
#
# orcarun.py <xyz file name> <charge> <multiplicity>
#
import sys
import numpy
import os
settings = { "ORCA":
                {
                    "METHOD": "MNDO",
                    "BASIS": "", #"pc-1"
                    "KEYWORDS": "engrad VerySlowConv",
                    "NPROC": "2"
                }
            }

def init(_settings):
    global settings
    settings.update(_settings)

def generateInput(inputfile, additional="", charge = None, multiplicity = None):
    if charge == None:
        charge = settings["GEOMETRIES"]["CHARGE"]
    if multiplicity == None:
        multiplicity = settings["GEOMETRIES"]["MULTIPLICITY"]
    with open(inputfile+".inp", 'w') as f:
        f.write("!" + settings["ORCA"]["METHOD"] + " " + settings["ORCA"]["BASIS"] + \
                " " + settings["ORCA"]["KEYWORDS"] + " " + additional + "\n")
        if "NPROC" in settings["ORCA"]:
            f.write("%pal\nnprocs " + settings["ORCA"]["NPROC"] + "\nend\n")
        f.write("*xyzfile " + charge + " " + \
                 multiplicity + " " + inputfile + "\n")

def eatLines(f,num):
    for i in range(num):
        f.readline()


import subprocess
import numpy as np
def callORCA(inputfile):
    if "ORCAPATH" in settings["ORCA"]:
        orcapath = settings["ORCA"]["ORCAPATH"]
    else:
        orcapath = os.environ.get("ORCAPATH")
        if not orcapath:
            print "Cannot determine ORCAPATH. Please set the ORCAPATH environment variable by 'export ORCAPATH=/full/path/to/orca/'."
            exit()
    command = orcapath + "orca " + inputfile + ".inp"
    process = subprocess.Popen(command.split(), stdout=subprocess.PIPE)
    output, error = process.communicate()
    with open(inputfile + ".out", 'w') as f:
        f.write(output)
    for line in output.split("\n"):
        if "Total Dipole Moment" in line:
            s = line.split(":")[-1]
            dipole = [x for x in s.split(" ") if x]
            with open(inputfile + ".engrad", "a") as f2:
                f2.write("#\n#DIPOLE MOMENT\n#\n")
                for i in dipole:
                    f2.write(i+"\n")

def readGrad(inputfile):
    with open(inputfile + ".engrad", "r") as f:
        eatLines(f,3)
        Natoms = int(f.readline())
        eatLines(f,3)
        Energy = float(f.readline())
        eatLines(f,3)
        grad = []
        for i in range(Natoms*3):
            grad.append(float(f.readline()))
        return (Energy, np.array(grad))

def readHessian(inputfile):
    matr = numpy.matrix([])
    with open(inputfile + ".hess", 'r') as f:
        while f.readline() != "$hessian\n":
            pass
        lines = int(f.readline())
        for k in range(lines/5+1):
            subm = [];
            f.readline()
            for i in range(lines):
                row = [float(y) for y in [x for x in f.readline().split(" ") if x][1:] ];
                subm.append(row);
            if matr.size == 0:
                matr = numpy.matrix(subm);
            else:
                matr = numpy.concatenate([matr, numpy.matrix(subm)], axis=1)
        return matr



def runOrca(prefix, Natoms, xyz, charge, multiplicity):
    inputfile = prefix+".xyz"
    with open(inputfile, 'w') as f:
        f.write(str(Natoms)+"\nGenerated by orcarun.py\n")
        f.write(xyz)
    generateInput(inputfile)
    callORCA(inputfile)
    return readGrad(inputfile)

def getOrcaHessian(prefix, Natoms, xyz, charge, multiplicity):
    inputfile = prefix+"_hess.xyz"
    if os.path.exists(inputfile):
        with open(inputfile, 'r') as f:
            old_content = f.read()
            new_content = str(Natoms)+"\nGenerated by orcarun.py\n"
            new_content += xyz
            if new_content == old_content and os.path.exists(inputfile + ".hess"):
                return readHessian(inputfile)
    with open(inputfile, 'w') as f:
        f.write(str(Natoms)+"\nGenerated by orcarun.py\n")
        f.write(xyz)
    generateInput(inputfile, "numfreq", charge = charge, multiplicity = multiplicity)
    callORCA(inputfile)
    return readHessian(inputfile)

if __name__ == "__main__":
    inputfile = sys.argv[1]
    charge = sys.argv[2]
    multiplicity = sys.argv[3]
    generateInput(inputfile)
    callORCA(inputfile)


